# NumPy Practice 
## for lab4

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the  introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy. 

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [4]:
# Create a 2-dimensional NumPy array using np.array()
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Create a 3-dimensional Numpy array using np.array()
arr = np.array([[[ 1,  2,  3],
                 [ 4,  5,  6],
                 [ 7,  8,  9]],

                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of  array.

In [10]:
# Attributes of 3-dimensional array
arr = np.random.randint(0, 11, size=(2, 3,3))
shape = arr.shape
ndim = arr.ndim
dtype = arr.dtype
size = arr.size
arr_type = type(arr)
output = (shape, ndim, dtype, size, arr_type)
output

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [11]:
# Create an array of shape (10, 2) with only ones
arr = np.ones((10, 2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
arr = np.zeros((7, 2, 3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
arr = np.arange(0, 100, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr = np.array([[8, 7],
                [9, 9],
                [1, 9],
                [1, 5],
                [8, 7],
                [6, 6],
                [0, 4]])
arr

array([[8, 7],
       [9, 9],
       [1, 9],
       [1, 5],
       [8, 7],
       [6, 6],
       [0, 4]])

In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr = np.random.rand(3, 5)
arr

array([[0.47708141, 0.36973769, 0.24423888, 0.80549397, 0.02410476],
       [0.05090772, 0.66356461, 0.53964887, 0.11367484, 0.09483077],
       [0.40450195, 0.95645816, 0.60465161, 0.4691733 , 0.82344121]])

In [21]:
# Set the random seed to 42
np.random.seed(42)

In [18]:
# Create a random array of numbers between 0 & 10 of size (4, 6)
arr = np.random.randint(0, 10, size=(4, 6))
arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
#write the answer here 
#

In [42]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr = np.random.randint(1, 11, size=(3, 7))
arr


array([[ 4,  1,  5,  7, 10, 10,  6],
       [ 5,  4,  2,  4, 10, 10,  3],
       [10,  1,  8,  5,  4,  8,  7]])

In [43]:
# Find the 0'th index of the latest array you created
arr_0th_index = arr[0]
arr_0th_index

array([ 4,  1,  5,  7, 10, 10,  6])

In [44]:
# Get the first 2 rows of latest array you created
first_two_rows = arr[:2]
first_two_rows

array([[ 4,  1,  5,  7, 10, 10,  6],
       [ 5,  4,  2,  4, 10, 10,  3]])

In [45]:
# Get the first 2 values of the first 2 rows of the latest array
first_two_values_first_two_rows = arr[:2, :2]
first_two_values_first_two_rows

array([[4, 1],
       [5, 4]])

In [47]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(0, 11, size=(3, 5)).astype(float)
ones_array = np.ones((3, 5))
random_array,ones_array

(array([[ 7.,  9., 10.,  1.,  2.],
        [ 1.,  2.,  6.,  0.,  9.],
        [ 7.,  9.,  9.,  9.,  1.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [48]:
# Add the two arrays together
result_array = random_array + ones_array
result_array

array([[ 8., 10., 11.,  2.,  3.],
       [ 2.,  3.,  7.,  1., 10.],
       [ 8., 10., 10., 10.,  2.]])

In [49]:
# Create another array of ones of shape (5, 3)
ones_array_5x3 = np.ones((5, 3))
ones_array_5x3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
# Try to add the array of ones and the other most recent array together
rec=ones_array_5x3+result_array

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
#لكن في هذه الحالة، الأبعاد غير متطابقة (حجم المصفوفة الأولى هو (3, 5) وحجم المصفوفة الثانية هو (5, 3))، لذا لا يمكن إجراء الجمع مباشرة بين المصفوفات.
#لحل هذه المشكلة، يمكن استخدام التكرار (broadcasting) أو تغيير الأبعاد لتصبح متوافقة. في هذه الحالة، يمكن استخدام np.tile لتكرار المصفوفة التي بحجم (3, 5) لجعل أبعادها تتطابق مع (5, 3)، ولكن هذا ليس مفيدًا دائمًا وقد يتطلب معالجة إضافية حسب ما تحتاجه.

In [51]:
# Create another array of ones of shape (3, 5)
ones_array_3x5 = np.ones((3, 5))
ones_array_3x5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
# Multiply the ones array with the latest array
result = random_array * ones_array_3x5
result

array([[ 7.,  9., 10.,  1.,  2.],
       [ 1.,  2.,  6.,  0.,  9.],
       [ 7.,  9.,  9.,  9.,  1.]])

In [53]:
# Find the mean of the latest array 
mean_value = np.mean(result)
mean_value

5.466666666666667

In [54]:
# Find the standard deviation of the latest array
std_dev = np.std(result)
std_dev

3.6672726771933517

In [55]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = result.reshape((3, 5, 1))
reshaped_array

array([[[ 7.],
        [ 9.],
        [10.],
        [ 1.],
        [ 2.]],

       [[ 1.],
        [ 2.],
        [ 6.],
        [ 0.],
        [ 9.]],

       [[ 7.],
        [ 9.],
        [ 9.],
        [ 9.],
        [ 1.]]])

In [60]:
# Transpose the latest array
transposed_array = reshaped_array.reshape((3, 5)).T
transposed_array

array([[ 7.,  1.,  7.],
       [ 9.,  2.,  9.],
       [10.,  6.,  9.],
       [ 1.,  0.,  9.],
       [ 2.,  9.,  1.]])

What does the transpose do?

In [61]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1 = np.random.randint(0, 11, size=(3, 3))
mat2 = np.random.randint(0, 11, size=(3, 2))
mat1, mat2

(array([[ 2,  8,  6],
        [ 3,  9,  4],
        [ 1, 10,  7]]),
 array([[3, 8],
        [4, 8],
        [3, 9]]))

In [64]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
shape = (4, 2)
array1 = np.random.randint(0, 11, size=shape)
array2 = np.random.randint(0, 11, size=shape)
array1, array2

(array([[10,  2],
        [ 0,  3],
        [ 8,  2],
        [ 8,  6]]),
 array([[3, 2],
        [9, 4],
        [4, 2],
        [8, 3]]))

In [65]:
# Compare the two arrays with '>'
comparison = array1 > array2
comparison

array([[ True, False],
       [False, False],
       [ True, False],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [67]:
# Compare the two arrays with '>='
comparison = array1 >= array2
comparison

array([[ True,  True],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [70]:
# Sort one of the arrays you just created in ascending order
array1 = np.array([[6, 5],
                   [9, 4],
                   [2, 7],
                   [1, 8]])
sorted_array1 = np.sort(array1, axis=0)
sorted_array1

array([[1, 4],
       [2, 5],
       [6, 7],
       [9, 8]])

In [72]:
#Sort the indexes of one of the arrays you just created
#hint ....search about argsort 
sorted_indices = np.argsort(array1, axis=0)
sorted_indices

array([[3, 1],
       [2, 0],
       [0, 2],
       [1, 3]], dtype=int64)

In [74]:
#convert  array to vector (1-dimensianal)
arr = np.array([[6, 9, 12], [8, 5, 2], [18, 21, 24]])
vector = arr.ravel()
vector

array([ 6,  9, 12,  8,  5,  2, 18, 21, 24])

In [75]:
# Create an array of normally distributed random numbers
normal_array = np.random.randn(3, 5)
normal_array

array([[ 1.15811087,  0.79166269,  0.62411982,  0.62834551, -0.01224677],
       [-0.89725437,  0.07580456, -0.67716171,  0.97511973, -0.14705738],
       [-0.8254972 , -0.32138584,  0.41293145, -0.56372455, -0.8222204 ]])

In [76]:
# Create an array with 10 evenly spaced numbers between 1 and 100
#hint search about linespace
evenly_spaced_array = np.linspace(1, 100, 10)
evenly_spaced_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])